=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenPipette::ActivityTypesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActivityTypesApi' do
  before do
    # run before each test
    @api_instance = OpenPipette::ActivityTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivityTypesApi' do
    it 'should create an instance of ActivityTypesApi' do
      expect(@api_instance).to be_instance_of(OpenPipette::ActivityTypesApi)
    end
  end

  # unit tests for add_activity_type
  # Add new activity type
  # Adds a new activity type.
  # @param [Hash] opts the optional parameters
  # @option opts [AddActivityTypeRequest] :add_activity_type_request 
  # @return [CreateUpdateDeleteActivityTypeResponse200]
  describe 'add_activity_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_activity_type
  # Delete an activity type
  # Marks an activity type as deleted.
  # @param id The ID of the activity type
  # @param [Hash] opts the optional parameters
  # @return [CreateUpdateDeleteActivityTypeResponse200]
  describe 'delete_activity_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_activity_types
  # Delete multiple activity types in bulk
  # Marks multiple activity types as deleted.
  # @param ids The comma-separated activity type IDs
  # @param [Hash] opts the optional parameters
  # @return [DeleteActivityTypesResponse200]
  describe 'delete_activity_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_activity_types
  # Get all activity types
  # Returns all activity types.
  # @param [Hash] opts the optional parameters
  # @return [GetActivityTypesResponse200]
  describe 'get_activity_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_activity_type
  # Update an activity type
  # Updates an activity type.
  # @param id The ID of the activity type
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateActivityTypeRequest] :update_activity_type_request 
  # @return [CreateUpdateDeleteActivityTypeResponse200]
  describe 'update_activity_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
