=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenPipette::ActivitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActivitiesApi' do
  before do
    # run before each test
    @api_instance = OpenPipette::ActivitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivitiesApi' do
    it 'should create an instance of ActivitiesApi' do
      expect(@api_instance).to be_instance_of(OpenPipette::ActivitiesApi)
    end
  end

  # unit tests for add_activity
  # Add an activity
  # Adds a new activity. Includes &#x60;more_activities_scheduled_in_context&#x60; property in response&#39;s &#x60;additional_data&#x60; which indicates whether there are more undone activities scheduled with the same deal, person or organization (depending on the supplied data). For more information, see the tutorial for &lt;a href&#x3D;\&quot;https://pipedrive.readme.io/docs/adding-an-activity\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;adding an activity&lt;/a&gt;. &lt;br /&gt; &lt;br /&gt; ***Starting from 30.09.2024, activity attendees will receive updates only if the activity owner has an active calendar sync***
  # @param [Hash] opts the optional parameters
  # @option opts [AddActivityRequest] :add_activity_request 
  # @return [AddActivityResponse200]
  describe 'add_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_activities
  # Delete multiple activities in bulk
  # Marks multiple activities as deleted. After 30 days, the activities will be permanently deleted.
  # @param ids The comma-separated IDs of activities that will be deleted
  # @param [Hash] opts the optional parameters
  # @return [DeleteActivitiesResponse200]
  describe 'delete_activities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_activity
  # Delete an activity
  # Marks an activity as deleted. After 30 days, the activity will be permanently deleted.
  # @param id The ID of the activity
  # @param [Hash] opts the optional parameters
  # @return [DeleteActivityResponse200]
  describe 'delete_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_activities
  # Get all activities assigned to a particular user
  # Returns all activities assigned to a particular user.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id The ID of the user whose activities will be fetched. If omitted, the user associated with the API token will be used. If 0, activities for all company users will be fetched based on the permission sets.
  # @option opts [Integer] :filter_id The ID of the filter to use (will narrow down results if used together with &#x60;user_id&#x60; parameter)
  # @option opts [String] :type The type of the activity, can be one type or multiple types separated by a comma. This is in correlation with the &#x60;key_string&#x60; parameter of ActivityTypes.
  # @option opts [Integer] :limit For pagination, the limit of entries to be returned. If not provided, 100 items will be returned.
  # @option opts [Integer] :start For pagination, the position that represents the first result for the page
  # @option opts [Date] :start_date Use the activity due date where you wish to begin fetching activities from. Insert due date in YYYY-MM-DD format.
  # @option opts [Date] :end_date Use the activity due date where you wish to stop fetching activities from. Insert due date in YYYY-MM-DD format.
  # @option opts [Float] :done Whether the activity is done or not. 0 &#x3D; Not done, 1 &#x3D; Done. If omitted returns both done and not done activities.
  # @return [GetActivitiesResponse200]
  describe 'get_activities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_activities_collection
  # Get all activities (BETA)
  # Returns all activities. This is a cursor-paginated endpoint that is currently in BETA. For more information, please refer to our documentation on &lt;a href&#x3D;\&quot;https://pipedrive.readme.io/docs/core-api-concepts-pagination\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;pagination&lt;/a&gt;. Please note that only global admins (those with global permissions) can access these endpoints. Users with regular permissions will receive a 403 response. Read more about global permissions &lt;a href&#x3D;\&quot;https://support.pipedrive.com/en/article/global-user-management\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;here&lt;/a&gt;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor For pagination, the marker (an opaque string value) representing the first item on the next page
  # @option opts [Integer] :limit For pagination, the limit of entries to be returned. If not provided, 100 items will be returned. Please note that a maximum value of 500 is allowed.
  # @option opts [String] :since The time boundary that points to the start of the range of data. Datetime in ISO 8601 format. E.g. 2022-11-01 08:55:59. Operates on the &#x60;update_time&#x60; field.
  # @option opts [String] :_until The time boundary that points to the end of the range of data. Datetime in ISO 8601 format. E.g. 2022-11-01 08:55:59. Operates on the &#x60;update_time&#x60; field.
  # @option opts [Integer] :user_id The ID of the user whose activities will be fetched. If omitted, all activities are returned.
  # @option opts [Boolean] :done Whether the activity is done or not. &#x60;false&#x60; &#x3D; Not done, &#x60;true&#x60; &#x3D; Done. If omitted, returns both done and not done activities.
  # @option opts [String] :type The type of the activity, can be one type or multiple types separated by a comma. This is in correlation with the &#x60;key_string&#x60; parameter of ActivityTypes.
  # @return [GetActivitiesCollectionResponse200]
  describe 'get_activities_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_activity
  # Get details of an activity
  # Returns the details of a specific activity.
  # @param id The ID of the activity
  # @param [Hash] opts the optional parameters
  # @return [GetActivityResponse200]
  describe 'get_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_activity
  # Update an activity
  # Updates an activity. Includes &#x60;more_activities_scheduled_in_context&#x60; property in response&#39;s &#x60;additional_data&#x60; which indicates whether there are more undone activities scheduled with the same deal, person or organization (depending on the supplied data). &lt;br /&gt; &lt;br /&gt; ***Starting from 30.09.2024, activity attendees will receive updates only if the activity owner has an active calendar sync***
  # @param id The ID of the activity
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateActivityRequest] :update_activity_request 
  # @return [UpdateActivityResponse200]
  describe 'update_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
