=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenPipette::LeadLabelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LeadLabelsApi' do
  before do
    # run before each test
    @api_instance = OpenPipette::LeadLabelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LeadLabelsApi' do
    it 'should create an instance of LeadLabelsApi' do
      expect(@api_instance).to be_instance_of(OpenPipette::LeadLabelsApi)
    end
  end

  # unit tests for add_lead_label
  # Add a lead label
  # Creates a lead label.
  # @param [Hash] opts the optional parameters
  # @option opts [AddLeadLabelRequest] :add_lead_label_request 
  # @return [AddOrUpdateLeadLabelResponse200]
  describe 'add_lead_label test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_lead_label
  # Delete a lead label
  # Deletes a specific lead label.
  # @param id The ID of the lead label
  # @param [Hash] opts the optional parameters
  # @return [LeadIdResponse200]
  describe 'delete_lead_label test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_lead_labels
  # Get all lead labels
  # Returns details of all lead labels. This endpoint does not support pagination and all labels are always returned.
  # @param [Hash] opts the optional parameters
  # @return [GetLeadLabelsResponse200]
  describe 'get_lead_labels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_lead_label
  # Update a lead label
  # Updates one or more properties of a lead label. Only properties included in the request will be updated. 
  # @param id The ID of the lead label
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateLeadLabelRequest] :update_lead_label_request 
  # @return [AddOrUpdateLeadLabelResponse200]
  describe 'update_lead_label test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
