=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenPipette::OrganizationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationsApi' do
  before do
    # run before each test
    @api_instance = OpenPipette::OrganizationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationsApi' do
    it 'should create an instance of OrganizationsApi' do
      expect(@api_instance).to be_instance_of(OpenPipette::OrganizationsApi)
    end
  end

  # unit tests for add_organization
  # Add an organization
  # Adds a new organization. Note that you can supply additional custom fields along with the request that are not described here. These custom fields are different for each Pipedrive account and can be recognized by long hashes as keys. To determine which custom fields exists, fetch the organizationFields and look for &#x60;key&#x60; values. For more information, see the tutorial for &lt;a href&#x3D;\&quot;https://pipedrive.readme.io/docs/adding-an-organization\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;adding an organization&lt;/a&gt;.
  # @param [Hash] opts the optional parameters
  # @option opts [AddOrganizationRequest] :add_organization_request 
  # @return [AddOrganizationResponse200]
  describe 'add_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_organization_follower
  # Add a follower to an organization
  # Adds a follower to an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [AddOrganizationFollowerRequest] :add_organization_follower_request 
  # @return [AddOrganizationFollowerResponse200]
  describe 'add_organization_follower test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization
  # Delete an organization
  # Marks an organization as deleted. After 30 days, the organization will be permanently deleted.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @return [DeleteOrganizationResponse200]
  describe 'delete_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization_follower
  # Delete a follower from an organization
  # Deletes a follower from an organization. You can retrieve the &#x60;follower_id&#x60; from the &lt;a href&#x3D;\&quot;https://developers.pipedrive.com/docs/api/v1/Organizations#getOrganizationFollowers\&quot;&gt;List followers of an organization&lt;/a&gt; endpoint.
  # @param id The ID of the organization
  # @param follower_id The ID of the follower
  # @param [Hash] opts the optional parameters
  # @return [DeleteOrganizationFollowerResponse200]
  describe 'delete_organization_follower test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organizations
  # Delete multiple organizations in bulk
  # Marks multiple organizations as deleted. After 30 days, the organizations will be permanently deleted.
  # @param ids The comma-separated IDs that will be deleted
  # @param [Hash] opts the optional parameters
  # @return [DeleteOrganizationsResponse200]
  describe 'delete_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization
  # Get details of an organization
  # Returns the details of an organization. Note that this also returns some additional fields which are not present when asking for all organizations. Also note that custom fields appear as long hashes in the resulting data. These hashes can be mapped against the &#x60;key&#x60; value of organizationFields.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @return [GetOrganizationResponse200]
  describe 'get_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_activities
  # List activities associated with an organization
  # Lists activities associated with an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @option opts [Float] :done Whether the activity is done or not. 0 &#x3D; Not done, 1 &#x3D; Done. If omitted returns both Done and Not done activities.
  # @option opts [String] :exclude A comma-separated string of activity IDs to exclude from result
  # @return [GetAssociatedActivitiesResponse200]
  describe 'get_organization_activities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_changelog
  # List updates about organization field values
  # Lists updates about field values of an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor For pagination, the marker (an opaque string value) representing the first item on the next page
  # @option opts [Integer] :limit Items shown per page
  # @return [GetChangelogResponse200]
  describe 'get_organization_changelog test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_deals
  # List deals associated with an organization
  # Lists deals associated with an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @option opts [String] :status Only fetch deals with a specific status. If omitted, all not deleted deals are returned. If set to deleted, deals that have been deleted up to 30 days ago will be included.
  # @option opts [String] :sort The field names and sorting mode separated by a comma (&#x60;field_name_1 ASC&#x60;, &#x60;field_name_2 DESC&#x60;). Only first-level field keys are supported (no nested keys).
  # @option opts [Float] :only_primary_association If set, only deals that are directly associated to the organization are fetched. If not set (default), all deals are fetched that are either directly or indirectly related to the organization. Indirect relations include relations through custom, organization-type fields and through persons of the given organization.
  # @return [GetAssociatedDealsResponse200]
  describe 'get_organization_deals test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_files
  # List files attached to an organization
  # Lists files associated with an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @option opts [String] :sort The field names and sorting mode separated by a comma (&#x60;field_name_1 ASC&#x60;, &#x60;field_name_2 DESC&#x60;). Only first-level field keys are supported (no nested keys). Supported fields: &#x60;id&#x60;, &#x60;user_id&#x60;, &#x60;deal_id&#x60;, &#x60;person_id&#x60;, &#x60;org_id&#x60;, &#x60;product_id&#x60;, &#x60;add_time&#x60;, &#x60;update_time&#x60;, &#x60;file_name&#x60;, &#x60;file_type&#x60;, &#x60;file_size&#x60;, &#x60;comment&#x60;.
  # @return [GetAssociatedFilesResponse200]
  describe 'get_organization_files test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_followers
  # List followers of an organization
  # Lists the followers of an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @return [GetAssociatedFollowersResponse2001]
  describe 'get_organization_followers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_mail_messages
  # List mail messages associated with an organization
  # Lists mail messages associated with an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @return [GetAssociatedMailMessagesResponse200]
  describe 'get_organization_mail_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_persons
  # List persons of an organization
  # Lists persons associated with an organization.&lt;br&gt;If a company uses the [Campaigns product](https://pipedrive.readme.io/docs/campaigns-in-pipedrive-api), then this endpoint will also return the &#x60;data.marketing_status&#x60; field.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @return [ListPersonsResponse200]
  describe 'get_organization_persons test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_updates
  # List updates about an organization
  # Lists updates about an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @option opts [String] :all_changes Whether to show custom field updates or not. 1 &#x3D; Include custom field changes. If omitted, returns changes without custom field updates.
  # @option opts [String] :items A comma-separated string for filtering out item specific updates. (Possible values - activity, plannedActivity, note, file, change, deal, follower, participant, mailMessage, mailMessageWithAttachment, invoice, activityFile, document).
  # @return [GetAssociatedUpdatesResponse200]
  describe 'get_organization_updates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_users
  # List permitted users
  # List users permitted to access an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @return [ListPermittedUsersResponse2001]
  describe 'get_organization_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organizations
  # Get all organizations
  # Returns all organizations.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id If supplied, only organizations owned by the given user will be returned. However, &#x60;filter_id&#x60; takes precedence over &#x60;user_id&#x60; when both are supplied.
  # @option opts [Integer] :filter_id The ID of the filter to use
  # @option opts [String] :first_char If supplied, only organizations whose name starts with the specified letter will be returned (case-insensitive)
  # @option opts [Integer] :start Pagination start
  # @option opts [Integer] :limit Items shown per page
  # @option opts [String] :sort The field names and sorting mode separated by a comma (&#x60;field_name_1 ASC&#x60;, &#x60;field_name_2 DESC&#x60;). Only first-level field keys are supported (no nested keys).
  # @return [GetOrganizationsResponse200]
  describe 'get_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organizations_collection
  # Get all organizations (BETA)
  # Returns all organizations. This is a cursor-paginated endpoint that is currently in BETA. For more information, please refer to our documentation on &lt;a href&#x3D;\&quot;https://pipedrive.readme.io/docs/core-api-concepts-pagination\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;pagination&lt;/a&gt;. Please note that only global admins (those with global permissions) can access these endpoints. Users with regular permissions will receive a 403 response. Read more about global permissions &lt;a href&#x3D;\&quot;https://support.pipedrive.com/en/article/global-user-management\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;here&lt;/a&gt;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor For pagination, the marker (an opaque string value) representing the first item on the next page
  # @option opts [Integer] :limit For pagination, the limit of entries to be returned. If not provided, 100 items will be returned. Please note that a maximum value of 500 is allowed.
  # @option opts [String] :since The time boundary that points to the start of the range of data. Datetime in ISO 8601 format. E.g. 2022-11-01 08:55:59. Operates on the &#x60;update_time&#x60; field.
  # @option opts [String] :_until The time boundary that points to the end of the range of data. Datetime in ISO 8601 format. E.g. 2022-11-01 08:55:59. Operates on the &#x60;update_time&#x60; field.
  # @option opts [Integer] :owner_id If supplied, only organizations owned by the given user will be returned
  # @option opts [String] :first_char If supplied, only organizations whose name starts with the specified letter will be returned (case-insensitive)
  # @return [GetOrganizationsCollection200Response]
  describe 'get_organizations_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merge_organizations
  # Merge two organizations
  # Merges an organization with another organization. For more information, see the tutorial for &lt;a href&#x3D;\&quot;https://pipedrive.readme.io/docs/merging-two-organizations\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;merging two organizations&lt;/a&gt;.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [MergeOrganizationsRequest] :merge_organizations_request 
  # @return [MergeOrganizationsResponse200]
  describe 'merge_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_organization
  # Search organizations
  # Searches all organizations by name, address, notes and/or custom fields. This endpoint is a wrapper of &lt;a href&#x3D;\&quot;https://developers.pipedrive.com/docs/api/v1/ItemSearch#searchItem\&quot;&gt;/v1/itemSearch&lt;/a&gt; with a narrower OAuth scope.
  # @param term The search term to look for. Minimum 2 characters (or 1 if using &#x60;exact_match&#x60;). Please note that the search term has to be URL encoded.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A comma-separated string array. The fields to perform the search from. Defaults to all of them. Only the following custom field types are searchable: &#x60;address&#x60;, &#x60;varchar&#x60;, &#x60;text&#x60;, &#x60;varchar_auto&#x60;, &#x60;double&#x60;, &#x60;monetary&#x60; and &#x60;phone&#x60;. Read more about searching by custom fields &lt;a href&#x3D;\&quot;https://support.pipedrive.com/en/article/search-finding-what-you-need#searching-by-custom-fields\&quot; target&#x3D;\&quot;_blank\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot;&gt;here&lt;/a&gt;.
  # @option opts [Boolean] :exact_match When enabled, only full exact matches against the given term are returned. It is &lt;b&gt;not&lt;/b&gt; case sensitive.
  # @option opts [Integer] :start Pagination start. Note that the pagination is based on main results and does not include related items when using &#x60;search_for_related_items&#x60; parameter.
  # @option opts [Integer] :limit Items shown per page
  # @return [SearchOrganizationResponse200]
  describe 'search_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization
  # Update an organization
  # Updates the properties of an organization.
  # @param id The ID of the organization
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateOrganizationRequest] :update_organization_request 
  # @return [UpdateOrganizationResponse200]
  describe 'update_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
