=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenPipette::OrganizationRelationshipsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationRelationshipsApi' do
  before do
    # run before each test
    @api_instance = OpenPipette::OrganizationRelationshipsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationRelationshipsApi' do
    it 'should create an instance of OrganizationRelationshipsApi' do
      expect(@api_instance).to be_instance_of(OpenPipette::OrganizationRelationshipsApi)
    end
  end

  # unit tests for add_organization_relationship
  # Create an organization relationship
  # Creates and returns an organization relationship.
  # @param [Hash] opts the optional parameters
  # @option opts [AddOrganizationRelationshipRequest] :add_organization_relationship_request 
  # @return [AddOrganizationRelationshipResponse200]
  describe 'add_organization_relationship test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization_relationship
  # Delete an organization relationship
  # Deletes an organization relationship and returns the deleted ID.
  # @param id The ID of the organization relationship
  # @param [Hash] opts the optional parameters
  # @return [DeleteOrganizationRelationshipResponse200]
  describe 'delete_organization_relationship test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_relationship
  # Get one organization relationship
  # Finds and returns an organization relationship from its ID.
  # @param id The ID of the organization relationship
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :org_id The ID of the base organization for the returned calculated values
  # @return [GetOrganizationRelationshipResponse200]
  describe 'get_organization_relationship test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_relationships
  # Get all relationships for organization
  # Gets all of the relationships for a supplied organization ID.
  # @param org_id The ID of the organization to get relationships for
  # @param [Hash] opts the optional parameters
  # @return [GetOrganizationRelationshipsResponse200]
  describe 'get_organization_relationships test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization_relationship
  # Update an organization relationship
  # Updates and returns an organization relationship.
  # @param id The ID of the organization relationship
  # @param [Hash] opts the optional parameters
  # @option opts [OrganizationRelationship] :organization_relationship 
  # @return [UpdateOrganizationRelationshipResponse200]
  describe 'update_organization_relationship test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
