=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'cgi'

module OpenPipette
  class ActivityTypesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Add new activity type
    # Adds a new activity type.
    # @param [Hash] opts the optional parameters
    # @option opts [AddActivityTypeRequest] :add_activity_type_request 
    # @return [CreateUpdateDeleteActivityTypeResponse200]
    def add_activity_type(opts = {})
      data, _status_code, _headers = add_activity_type_with_http_info(opts)
      data
    end

    # Add new activity type
    # Adds a new activity type.
    # @param [Hash] opts the optional parameters
    # @option opts [AddActivityTypeRequest] :add_activity_type_request 
    # @return [Array<(CreateUpdateDeleteActivityTypeResponse200, Integer, Hash)>] CreateUpdateDeleteActivityTypeResponse200 data, response status code and response headers
    def add_activity_type_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ActivityTypesApi.add_activity_type ...'
      end
      # resource path
      local_var_path = '/activityTypes'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'add_activity_type_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'CreateUpdateDeleteActivityTypeResponse200'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key', 'oauth2']

      new_options = opts.merge(
        :operation => :"ActivityTypesApi.add_activity_type",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ActivityTypesApi#add_activity_type\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete an activity type
    # Marks an activity type as deleted.
    # @param id [Integer] The ID of the activity type
    # @param [Hash] opts the optional parameters
    # @return [CreateUpdateDeleteActivityTypeResponse200]
    def delete_activity_type(id, opts = {})
      data, _status_code, _headers = delete_activity_type_with_http_info(id, opts)
      data
    end

    # Delete an activity type
    # Marks an activity type as deleted.
    # @param id [Integer] The ID of the activity type
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateUpdateDeleteActivityTypeResponse200, Integer, Hash)>] CreateUpdateDeleteActivityTypeResponse200 data, response status code and response headers
    def delete_activity_type_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ActivityTypesApi.delete_activity_type ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ActivityTypesApi.delete_activity_type"
      end
      # resource path
      local_var_path = '/activityTypes/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'CreateUpdateDeleteActivityTypeResponse200'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key', 'oauth2']

      new_options = opts.merge(
        :operation => :"ActivityTypesApi.delete_activity_type",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ActivityTypesApi#delete_activity_type\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete multiple activity types in bulk
    # Marks multiple activity types as deleted.
    # @param ids [String] The comma-separated activity type IDs
    # @param [Hash] opts the optional parameters
    # @return [DeleteActivityTypesResponse200]
    def delete_activity_types(ids, opts = {})
      data, _status_code, _headers = delete_activity_types_with_http_info(ids, opts)
      data
    end

    # Delete multiple activity types in bulk
    # Marks multiple activity types as deleted.
    # @param ids [String] The comma-separated activity type IDs
    # @param [Hash] opts the optional parameters
    # @return [Array<(DeleteActivityTypesResponse200, Integer, Hash)>] DeleteActivityTypesResponse200 data, response status code and response headers
    def delete_activity_types_with_http_info(ids, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ActivityTypesApi.delete_activity_types ...'
      end
      # verify the required parameter 'ids' is set
      if @api_client.config.client_side_validation && ids.nil?
        fail ArgumentError, "Missing the required parameter 'ids' when calling ActivityTypesApi.delete_activity_types"
      end
      # resource path
      local_var_path = '/activityTypes'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'ids'] = ids

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'DeleteActivityTypesResponse200'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key', 'oauth2']

      new_options = opts.merge(
        :operation => :"ActivityTypesApi.delete_activity_types",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ActivityTypesApi#delete_activity_types\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get all activity types
    # Returns all activity types.
    # @param [Hash] opts the optional parameters
    # @return [GetActivityTypesResponse200]
    def get_activity_types(opts = {})
      data, _status_code, _headers = get_activity_types_with_http_info(opts)
      data
    end

    # Get all activity types
    # Returns all activity types.
    # @param [Hash] opts the optional parameters
    # @return [Array<(GetActivityTypesResponse200, Integer, Hash)>] GetActivityTypesResponse200 data, response status code and response headers
    def get_activity_types_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ActivityTypesApi.get_activity_types ...'
      end
      # resource path
      local_var_path = '/activityTypes'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'GetActivityTypesResponse200'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key', 'oauth2']

      new_options = opts.merge(
        :operation => :"ActivityTypesApi.get_activity_types",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ActivityTypesApi#get_activity_types\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an activity type
    # Updates an activity type.
    # @param id [Integer] The ID of the activity type
    # @param [Hash] opts the optional parameters
    # @option opts [UpdateActivityTypeRequest] :update_activity_type_request 
    # @return [CreateUpdateDeleteActivityTypeResponse200]
    def update_activity_type(id, opts = {})
      data, _status_code, _headers = update_activity_type_with_http_info(id, opts)
      data
    end

    # Update an activity type
    # Updates an activity type.
    # @param id [Integer] The ID of the activity type
    # @param [Hash] opts the optional parameters
    # @option opts [UpdateActivityTypeRequest] :update_activity_type_request 
    # @return [Array<(CreateUpdateDeleteActivityTypeResponse200, Integer, Hash)>] CreateUpdateDeleteActivityTypeResponse200 data, response status code and response headers
    def update_activity_type_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ActivityTypesApi.update_activity_type ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ActivityTypesApi.update_activity_type"
      end
      # resource path
      local_var_path = '/activityTypes/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'update_activity_type_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'CreateUpdateDeleteActivityTypeResponse200'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key', 'oauth2']

      new_options = opts.merge(
        :operation => :"ActivityTypesApi.update_activity_type",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ActivityTypesApi#update_activity_type\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
