=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays do
  let(:instance) { OpenPipette::GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays.new }

  describe 'test an instance of GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays' do
    it 'should create an instance of GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays)
    end
  end

  describe 'test attribute "across_all_stages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "by_stages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
