=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::GetOrganizationRelationshipsResponse200AllOfRelatedObjects
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::GetOrganizationRelationshipsResponse200AllOfRelatedObjects do
  let(:instance) { OpenPipette::GetOrganizationRelationshipsResponse200AllOfRelatedObjects.new }

  describe 'test an instance of GetOrganizationRelationshipsResponse200AllOfRelatedObjects' do
    it 'should create an instance of GetOrganizationRelationshipsResponse200AllOfRelatedObjects' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::GetOrganizationRelationshipsResponse200AllOfRelatedObjects)
    end
  end

  describe 'test attribute "organization"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
