=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::GetRecentsResponse200DataInnerAnyOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::GetRecentsResponse200DataInnerAnyOf do
  let(:instance) { OpenPipette::GetRecentsResponse200DataInnerAnyOf.new }

  describe 'test an instance of GetRecentsResponse200DataInnerAnyOf' do
    it 'should create an instance of GetRecentsResponse200DataInnerAnyOf' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::GetRecentsResponse200DataInnerAnyOf)
    end
  end

  describe 'test attribute "item"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["activity"])
      # validator.allowable_values.each do |value|
      #   expect { instance.item = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
