=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::GetActivitiesResponse200RelatedObjectsDeal
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::GetActivitiesResponse200RelatedObjectsDeal do
  let(:instance) { OpenPipette::GetActivitiesResponse200RelatedObjectsDeal.new }

  describe 'test an instance of GetActivitiesResponse200RelatedObjectsDeal' do
    it 'should create an instance of GetActivitiesResponse200RelatedObjectsDeal' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::GetActivitiesResponse200RelatedObjectsDeal)
    end
  end

  describe 'test attribute "deal_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
