=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::GetProjectTemplateResponse200
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::GetProjectTemplateResponse200 do
  let(:instance) { OpenPipette::GetProjectTemplateResponse200.new }

  describe 'test an instance of GetProjectTemplateResponse200' do
    it 'should create an instance of GetProjectTemplateResponse200' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::GetProjectTemplateResponse200)
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "additional_data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
