=begin
#Pipedrive API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenPipette::ReceiveMessage200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenPipette::ReceiveMessage200Response do
  let(:instance) { OpenPipette::ReceiveMessage200Response.new }

  describe 'test an instance of ReceiveMessage200Response' do
    it 'should create an instance of ReceiveMessage200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenPipette::ReceiveMessage200Response)
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
